// Japan-test-project/japan-react/component/modal.tsx

const ModelData = ({ data, modalRef, hideModal }) => {
    return (
        <>
            <div className="modal fade" tabIndex={-1} ref={modalRef}>
                <div className="modal-dialog">
                    <div className="modal-content">
                        <div className="modal-header">
                            <h2
                                className="modal-title display-6"
                                id="staticBackdropLabel"
                            >
                                {data.DisplayName}
                            </h2>
                            <button
                                type="button"
                                className="btn-close"
                                aria-label="Close"
                                onClick={hideModal}
                            ></button>
                        </div>
                        <div className="modal-body">
                            <p className="">
                                <strong>Name : </strong>
                                <span>{data.Name || "N/A"}</span>
                            </p>
                            <p className="">
                                <strong>Brand : </strong>
                                <span>{data.Brand || "N/A"}</span>
                            </p>
                            <p className="">
                                <strong>Brand : </strong>
                                <span>{data.Brand || "N/A"}</span>
                            </p>
                            <p className="N/A">
                                <strong>Model : </strong>
                                <span>{data.Model || "N/A"}</span>
                            </p>
                            <p className="N/A">
                                <strong>Group Id : </strong>
                                <span>{data.GroupId || "N/A"}</span>
                            </p>
                            <p className="N/A">
                                <strong>Protocol Order : </strong>
                                <span>{data.ProtocolOrder || "N/A"}</span>
                            </p>
                            <p className="N/A">
                                <strong>Status : </strong>
                                <span>{data.Status || "N/A"}</span>
                            </p>
                            <p className="N/A">
                                <strong>Description : </strong>
                                <span>{data.Description || "N/A"}</span>
                            </p>
                        </div>
                        <div className="modal-footer">
                            <button
                                type="button"
                                className="btn btn-secondary"
                                onClick={hideModal}
                            >
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default ModelData;

// Japan-test-project/japan-vue/src/components/modal.vue
<template>
    <div id='modal' class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title display-6" id="staticBackdropLabel">
                        {{ modalData.DisplayName }}
                    </h2>
                    <button type="button" @click="close" class="close btn">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="">
                        <strong>Name : </strong>
                        <span>{{ modalData.Name || "N/A" }}</span>
                    </p>
                    <p class="">
                        <strong>Brand : </strong>
                        <span>{{ modalData.Brand || "N/A" }}</span>
                    </p>
                    <p class="">
                        <strong>Brand : </strong>
                        <span>{{ modalData.Brand || "N/A" }}</span>
                    </p>
                    <p class="N/A">
                        <strong>Model : </strong>
                        <span>{{ modalData.Model || "N/A" }}</span>
                    </p>
                    <p class="N/A">
                        <strong>Group Id : </strong>
                        <span>{{ modalData.GroupId || "N/A" }}</span>
                    </p>
                    <p class="N/A">
                        <strong>Protocol Order : </strong>
                        <span>{{ modalData.ProtocolOrder || "N/A" }}</span>
                    </p>
                    <p class="N/A">
                        <strong>Status : </strong>
                        <span>{{ modalData.Status || "N/A" }}</span>
                    </p>
                    <p class="N/A">
                        <strong>Description : </strong>
                        <span>{{ modalData.Description || "N/A" }}</span>
                    </p>
                </div>
                <div class="modal-footer">
                    <button
                        type="button"
                        class="btn btn-secondary"
                        @click="close"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { defineComponent } from "@vue/composition-api";
import { Modal } from "bootstrap";
export default defineComponent({
    name: "ModalData",
    props: ["modalData", "close"],
});
</script>
